# Generated by Django 4.2.5 on 2023-10-01 20:15

import categories.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0004_alter_categories_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='author',
            field=models.ForeignKey(default=categories.models.Categories.get_admin_users, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
