# Generated by Django 4.2.5 on 2023-10-02 23:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_categories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Choise color'),
        ),
    ]
