# Generated by Django 4.2.5 on 2023-10-02 23:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_categories_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#f3f4f6', image_field=None, max_length=25, samples=None, verbose_name='Choise color'),
        ),
    ]
