# Generated by Django 4.2.5 on 2023-10-03 00:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_categories_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#F3F4F6', image_field=None, max_length=25, samples=None, verbose_name='Choise color'),
        ),
    ]
