# Generated by Django 4.2.5 on 2023-10-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_categories_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
    ]
