# Generated by Django 4.2.5 on 2023-10-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='Articles',
        ),
    ]
